@MSilvaPizza_HostAddress = http://localhost:5250

POST {{MSilvaPizza_HostAddress}}/pizza/
Content-Type: application/json

{
  "name": "Margherita Especial",
  "isGlutenFree": false,
  "description": "A clássica italiana com muçarela de búfala fresca, tomates selecionados e folhas de manjericão.",
  "width": "35cm",
  "doughType": "Massa Fina",
  "ingredients": [
    "Molho de tomate artesanal",
    "Muçarela de búfala",
    "Tomate cereja",
    "Manjericão fresco",
    "Azeite extra virgem"
  ],
  "price": 59.90,
  "imageUrl": "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500"
}

###
GET {{MSilvaPizza_HostAddress}}/pizza
Accept: application/json

###

GET {{MSilvaPizza_HostAddress}}/pizza/80b463ae-36c6-4477-9d52-88dee32cf30a
Accept: application/json

###

PATCH  {{MSilvaPizza_HostAddress}}/pizza/80b463ae-36c6-4477-9d52-88dee32cf30a
Content-Type: application/json

{
    "uuid": "80b463ae-36c6-4477-9d52-88dee32cf30a",
    "name": "Mussarela",
    "isGlutenFree": true,
}
 
###
DELETE {{MSilvaPizza_HostAddress}}/pizza/80b463ae-36c6-4477-9d52-88dee32cf30a
Accept: application/json


# ________________USERS__________________________________________________

### CRIAR
POST {{MSilvaPizza_HostAddress}}/user/
Content-Type: application/json

{
  "username": "Fulano",
  "password": "passowrd"
}

### LOGAR
POST {{MSilvaPizza_HostAddress}}/user/login
Content-Type: application/json

{
  "username": "Fulano",
  "password": "passowrd"
}

### BUSCAR
GET {{MSilvaPizza_HostAddress}}/user/aca6b28a-6eb0-47cd-98a7-e62a66c12104
Accept: application/json

### ATUALIZAR
PATCH  {{MSilvaPizza_HostAddress}}/user/aca6b28a-6eb0-47cd-98a7-e62a66c12104
Content-Type: application/json

{
  "uuid": "aca6b28a-6eb0-47cd-98a7-e62a66c12104",
  "username": "Fulano",
  "password": "passowrd2"
}